baseURL = ""
languageCode = "en-us"
title = "NHS Service Finder"
theme = "hugo-acecentre-theme"

[outputFormats]
  [outputFormats.rawdata]
    mediaType = "application/json"
    baseName = "rawdata"
    isPlainText = true
  [outputFormats.kml]
    mediaType = "application/xml"
    baseName = "kml"
    isPlainText = true


[outputs]
page = [ "html", "rawdata" ]
taxonomy = [ "html", "rawdata" ]

[taxonomies]
ccgservice = "ccgservices"
ccgcode = "ccgcodes"

[permalinks]
page = "/:slug/"

[params]
# Favicon
favicon_32 = "images/icon/ace-icon-32x32.png"
favicon_192 = "images/icon/ace-icon-192x192.png"
favicon_180 = "images/icon/ace-icon-180x180.png"
favicon_270 = "images/icon/ace-icon-270x270.png"
