backend:
  {name: github,repo: rajbhojani77/test-repo}

branch: master 

collections:
  - name: "nhs-service" 
    label: "Service" 
    folder: "content/ccg" 
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}