backend:
  name: github
  repo: acecentre/nhs-service-finder
  branch: master 

media_folder: "static/images/uploads"
media_library:
  name: uploads    
  
collections:
  - name: "nhs-service" 
    label: "Service" 
    folder: "content/ccg" 
    create: false 
    slug: "{{fields.serviceid}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Service ID", name: "serviceid", widget: "string"}
      - {label: "Service Name", name: "servicename", widget: "string"}
      - {label: "Service Colour", name: "servicecolor", widget: "string", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Alternative web address", name: "cm_listing_link", widget: "string", required: false}
      - {label: "Contact Phone #", name: "contactphone", widget: "string"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Address", name: "address", widget: "text"}
      - {label: "Services offered", name: "ccgservices", widget: "select", options: ["aac", "ec", "wcs"], multiple: true}
      - {label: "CCG Codes covered", name: "ccgcodes", widget: "select", multiple: true, options:
            [{ label: "NHS Airedale, Wharfedale and Craven CCG", value: "e38000001" }, 
{ label: "NHS Ashford CCG", value: "e38000002" }, 
{ label: "NHS Barking and Dagenham CCG", value: "e38000004" }, 
{ label: "NHS Barnet CCG", value: "e38000005" }, 
{ label: "NHS Barnsley CCG", value: "e38000006" }, 
{ label: "NHS Basildon and Brentwood CCG", value: "e38000007" }, 
{ label: "NHS Bassetlaw CCG", value: "e38000008" }, 
{ label: "NHS Bath and North East Somerset CCG", value: "e38000009" }, 
{ label: "NHS Bedfordshire CCG", value: "e38000010" }, 
{ label: "NHS Bexley CCG", value: "e38000011" }, 
{ label: "NHS Blackburn with Darwen CCG", value: "e38000014" }, 
{ label: "NHS Blackpool CCG", value: "e38000015" }, 
{ label: "NHS Bolton CCG", value: "e38000016" }, 
{ label: "NHS Bradford City CCG", value: "e38000018" }, 
{ label: "NHS Bradford Districts CCG", value: "e38000019" }, 
{ label: "NHS Brent CCG", value: "e38000020" }, 
{ label: "NHS Brighton and Hove CCG", value: "e38000021" }, 
{ label: "NHS Bromley CCG", value: "e38000023" }, 
{ label: "NHS Bury CCG", value: "e38000024" }, 
{ label: "NHS Calderdale CCG", value: "e38000025" }, 
{ label: "NHS Cambridgeshire and Peterborough CCG", value: "e38000026" }, 
{ label: "NHS Camden CCG", value: "e38000027" }, 
{ label: "NHS Cannock Chase CCG", value: "e38000028" }, 
{ label: "NHS Canterbury and Coastal CCG", value: "e38000029" }, 
{ label: "NHS Castle Point and Rochford CCG", value: "e38000030" }, 
{ label: "NHS Central London (Westminster) CCG", value: "e38000031" }, 
{ label: "NHS Chorley and South Ribble CCG", value: "e38000034" }, 
{ label: "NHS City and Hackney CCG", value: "e38000035" }, 
{ label: "NHS Corby CCG", value: "e38000037" }, 
{ label: "NHS Coventry and Rugby CCG", value: "e38000038" }, 
{ label: "NHS Crawley CCG", value: "e38000039" }, 
{ label: "NHS Croydon CCG", value: "e38000040" }, 
{ label: "NHS Darlington CCG", value: "e38000042" }, 
{ label: "NHS Dartford, Gravesham and Swanley CCG", value: "e38000043" }, 
{ label: "NHS Doncaster CCG", value: "e38000044" }, 
{ label: "NHS Dorset CCG", value: "e38000045" }, 
{ label: "NHS Dudley CCG", value: "e38000046" }, 
{ label: "NHS Durham Dales, Easington and Sedgefield CCG", value: "e38000047"},
{ label: "NHS Ealing CCG", value: "e38000048" }, 
{ label: "NHS East and North Hertfordshire CCG", value: "e38000049" }, 
{ label: "NHS East Lancashire CCG", value: "e38000050" }, 
{ label: "NHS East Leicestershire and Rutland CCG", value: "e38000051" }, 
{ label: "NHS East Riding of Yorkshire CCG", value: "e38000052" }, 
{ label: "NHS East Staffordshire CCG", value: "e38000053" }, 
{ label: "NHS East Surrey CCG", value: "e38000054" }, 
{ label: "NHS Eastbourne, Hailsham and Seaford CCG", value: "e38000055" }, 
{ label: "NHS Eastern Cheshire CCG", value: "e38000056" }, 
{ label: "NHS Enfield CCG", value: "e38000057" }, 
{ label: "NHS Fareham and Gosport CCG", value: "e38000059" }, 
{ label: "NHS Gloucestershire CCG", value: "e38000062" }, 
{ label: "NHS Great Yarmouth and Waveney CCG", value: "e38000063" }, 
{ label: "NHS Greater Huddersfield CCG", value: "e38000064" }, 
{ label: "NHS Greenwich CCG", value: "e38000066" }, 
{ label: "NHS Halton CCG", value: "e38000068" }, 
{ label: "NHS Hambleton, Richmondshire and Whitby CCG", value: "e38000069" }, 
{ label: "NHS Hammersmith and Fulham CCG", value: "e38000070" }, 
{ label: "NHS Haringey CCG", value: "e38000072" }, 
{ label: "NHS Harrogate and Rural District CCG", value: "e38000073" }, 
{ label: "NHS Harrow CCG", value: "e38000074" }, 
{ label: "NHS Hartlepool and Stockton-on-Tees CCG", value: "e38000075" }, 
{ label: "NHS Hastings and Rother CCG", value: "e38000076" }, 
{ label: "NHS Havering CCG", value: "e38000077" }, 
{ label: "NHS Herefordshire CCG", value: "e38000078" }, 
{ label: "NHS Herts Valleys CCG", value: "e38000079" }, 
{ label: "NHS South Warwickshire CCG", value: "e38000164" }, 
{ label: "NHS South West Lincolnshire CCG", value: "e38000165" }, 
{ label: "NHS South Worcestershire CCG", value: "e38000166" }, 
{ label: "NHS Southampton CCG", value: "e38000167" }, 
{ label: "NHS Southend CCG", value: "e38000168" }, 
{ label: "NHS Southport and Formby CCG", value: "e38000170" }, 
{ label: "NHS Southwark CCG", value: "e38000171" }, 
{ label: "NHS St Helens CCG", value: "e38000172" }, 
{ label: "NHS Stafford and Surrounds CCG", value: "e38000173" }, 
{ label: "NHS Stockport CCG", value: "e38000174" }, 
{ label: "NHS Stoke on Trent CCG", value: "e38000175" }, 
{ label: "NHS Sunderland CCG", value: "e38000176" }, 
{ label: "NHS Surrey Downs CCG", value: "e38000177" }, 
{ label: "NHS Surrey Heath CCG", value: "e38000178" }, 
{ label: "NHS Sutton CCG", value: "e38000179" }, 
{ label: "NHS Swale CCG", value: "e38000180" }, 
{ label: "NHS Swindon CCG", value: "e38000181" }, 
{ label: "NHS Tameside and Glossop CCG", value: "e38000182" }, 
{ label: "NHS Telford and Wrekin CCG", value: "e38000183" }, 
{ label: "NHS Thanet CCG", value: "e38000184" }, 
{ label: "NHS Thurrock CCG", value: "e38000185" }, 
{ label: "NHS Tower Hamlets CCG", value: "e38000186" }, 
{ label: "NHS Trafford CCG", value: "e38000187" }, 
{ label: "NHS Vale of York CCG", value: "e38000188" }, 
{ label: "NHS Vale Royal CCG", value: "e38000189" }, 
{ label: "NHS Wakefield CCG", value: "e38000190" }, 
{ label: "NHS Walsall CCG", value: "e38000191" }, 
{ label: "NHS Waltham Forest CCG", value: "e38000192" }, 
{ label: "NHS Wandsworth CCG", value: "e38000193" }, 
{ label: "NHS Warrington CCG", value: "e38000194" }, 
{ label: "NHS Warwickshire North CCG", value: "e38000195" }, 
{ label: "NHS West Cheshire CCG", value: "e38000196" }, 
{ label: "NHS West Essex CCG", value: "e38000197" }, 
{ label: "NHS West Hampshire CCG", value: "e38000198" }, 
{ label: "NHS West Kent CCG", value: "e38000199" }, 
{ label: "NHS West Lancashire CCG", value: "e38000200" }, 
{ label: "NHS West Leicestershire CCG", value: "e38000201" }, 
{ label: "NHS West London CCG", value: "e38000202" }, 
{ label: "NHS West Norfolk CCG", value: "e38000203" }, 
{ label: "NHS West Suffolk CCG", value: "e38000204" }, 
{ label: "NHS Wigan Borough CCG", value: "e38000205" }, 
{ label: "NHS Wiltshire CCG", value: "e38000206" }, 
{ label: "NHS Wirral CCG", value: "e38000208" }, 
{ label: "NHS Wolverhampton CCG", value: "e38000210" }, 
{ label: "NHS Wyre Forest CCG", value: "e38000211" }, 
{ label: "NHS Newcastle Gateshead CCG", value: "e38000212" }, 
{ label: "NHS Coastal West Sussex CCG", value: "e38000213" }, 
{ label: "NHS Guildford and Waverley CCG", value: "e38000214" }, 
{ label: "NHS North Cumbria CCG", value: "e38000215" }, 
{ label: "NHS Manchester CCG", value: "e38000217" }, 
{ label: "NHS Norwich CCG", value: "e38000218" }, 
{ label: "NHS South Norfolk CCG", value: "e38000219" }, 
{ label: "NHS Birmingham and Solihull CCG", value: "e38000220" }, 
{ label: "NHS Berkshire West CCG", value: "e38000221" }, 
{ label: "NHS Bristol, North Somerset and South Gloucestershire CCG", value: "e38000222" }, 
{ label: "NHS Buckinghamshire CCG", value: "e38000223" }, 
{ label: "NHS East Berkshire CCG", value: "e38000224" }, 
{ label: "NHS Leeds CCG", value: "e38000225" }, 
{ label: "NHS Fylde and Wyre CCG", value: "e38000226" }, 
{ label: "NHS Greater Preston CCG", value: "e38000227" }, 
{ label: "NHS Morecambe Bay CCG", value: "e38000228" }, 
{ label: "NHS Derby and Derbyshire CCG", value: "e38000229" }, 
{ label: "NHS Devon CCG", value: "e38000230" }, 
{ label: "NHS Heywood, Middleton and Rochdale CCG", value: "e38000080" }, 
{ label: "NHS High Weald Lewes Havens CCG", value: "e38000081" }, 
{ label: "NHS Hillingdon CCG", value: "e38000082" }, 
{ label: "NHS Horsham and Mid Sussex CCG", value: "e38000083" }, 
{ label: "NHS Hounslow CCG", value: "e38000084" }, 
{ label: "NHS Hull CCG", value: "e38000085" }, 
{ label: "NHS Ipswich and East Suffolk CCG", value: "e38000086" }, 
{ label: "NHS Isle of Wight CCG", value: "e38000087" }, 
{ label: "NHS Islington CCG", value: "e38000088" }, 
{ label: "NHS Kernow CCG", value: "e38000089" }, 
{ label: "NHS Kingston CCG", value: "e38000090" }, 
{ label: "NHS Knowsley CCG", value: "e38000091" }, 
{ label: "NHS Lambeth CCG", value: "e38000092" }, 
{ label: "NHS Leicester City CCG", value: "e38000097" }, 
{ label: "NHS Lewisham CCG", value: "e38000098" }, 
{ label: "NHS Lincolnshire East CCG", value: "e38000099" }, 
{ label: "NHS Lincolnshire West CCG", value: "e38000100" }, 
{ label: "NHS Liverpool CCG", value: "e38000101" }, 
{ label: "NHS Luton CCG", value: "e38000102" }, 
{ label: "NHS Mansfield and Ashfield CCG", value: "e38000103" }, 
{ label: "NHS Medway CCG", value: "e38000104" }, 
{ label: "NHS Merton CCG", value: "e38000105" }, 
{ label: "NHS Mid Essex CCG", value: "e38000106" }, 
{ label: "NHS Milton Keynes CCG", value: "e38000107" }, 
{ label: "NHS Nene CCG", value: "e38000108" }, 
{ label: "NHS Newark and Sherwood CCG", value: "e38000109" }, 
{ label: "NHS Newham CCG", value: "e38000113" }, 
{ label: "NHS North Durham CCG", value: "e38000116" }, 
{ label: "NHS North East Essex CCG", value: "e38000117" }, 
{ label: "NHS North East Hampshire and Farnham CCG", value: "e38000118" }, 
{ label: "NHS North East Lincolnshire CCG", value: "e38000119" }, 
{ label: "NHS North Hampshire CCG", value: "e38000120" }, 
{ label: "NHS North Kirklees CCG", value: "e38000121" }, 
{ label: "NHS North Lincolnshire CCG", value: "e38000122" }, 
{ label: "NHS North Norfolk CCG", value: "e38000124" }, 
{ label: "NHS North Staffordshire CCG", value: "e38000126" }, 
{ label: "NHS North Tyneside CCG", value: "e38000127" }, 
{ label: "NHS North West Surrey CCG", value: "e38000128" }, 
{ label: "NHS Northumberland CCG", value: "e38000130" }, 
{ label: "NHS Nottingham City CCG", value: "e38000132" }, 
{ label: "NHS Nottingham North and East CCG", value: "e38000133" }, 
{ label: "NHS Nottingham West CCG", value: "e38000134" }, 
{ label: "NHS Oldham CCG", value: "e38000135" }, 
{ label: "NHS Oxfordshire CCG", value: "e38000136" }, 
{ label: "NHS Portsmouth CCG", value: "e38000137" }, 
{ label: "NHS Redbridge CCG", value: "e38000138" }, 
{ label: "NHS Redditch and Bromsgrove CCG", value: "e38000139" }, 
{ label: "NHS Richmond CCG", value: "e38000140" }, 
{ label: "NHS Rotherham CCG", value: "e38000141" }, 
{ label: "NHS Rushcliffe CCG", value: "e38000142" }, 
{ label: "NHS Salford CCG", value: "e38000143" }, 
{ label: "NHS Sandwell and West Birmingham CCG", value: "e38000144" }, 
{ label: "NHS Scarborough and Ryedale CCG", value: "e38000145" }, 
{ label: "NHS Sheffield CCG", value: "e38000146" }, 
{ label: "NHS Shropshire CCG", value: "e38000147" }, 
{ label: "NHS Somerset CCG", value: "e38000150" }, 
{ label: "NHS South Cheshire CCG", value: "e38000151" }, 
{ label: "NHS South East Staffordshire and Seisdon Peninsula CCG", value: "e38000153" }, 
{ label: "NHS South Eastern Hampshire CCG", value: "e38000154" }, 
{ label: "NHS South Kent Coast CCG", value: "e38000156" }, 
{ label: "NHS South Lincolnshire CCG", value: "e38000157" }, 
{ label: "NHS South Sefton CCG", value: "e38000161" }, 
{ label: "NHS South Tees CCG", value: "e38000162" }, 
{ label: "NHS South Tyneside CCG", value: "e38000163" }]
        }
      - {label: "Body", name: "body", widget: "markdown"}